### ISSUE TITLE
pulumi-command v1

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-command#449]
Tracking issue for the 1.0 release of the `command` provider.

## Must have

- [x] https://github.com/pulumi/pulumi-command/issues/48
- [x] https://github.com/pulumi/pulumi-command/issues/16
- [x] https://github.com/pulumi/pulumi-command/issues/23
- [x] https://github.com/pulumi/pulumi-command/issues/33
- [x] https://github.com/pulumi/pulumi-command/issues/42
- [ ] https://github.com/pulumi/pulumi-command/issues/196

## For consideration

- [ ] https://github.com/pulumi/pulumi-command/issues/124
- [x] https://github.com/pulumi/pulumi-command/issues/401
- [x] https://github.com/pulumi/pulumi-command/issues/40

### Needs design
- [ ] https://github.com/pulumi/pulumi-command/issues/49
- [ ] https://github.com/pulumi/pulumi-command/issues/432
- [ ] https://github.com/pulumi/pulumi-command/issues/433

**Comment by lukehoban** [comment]
We delivered the 1.0 release of Pulumi Command provider. 🎉 

* Blog: https://www.pulumi.com/blog/command-provider-ga/
* Registry: https://www.pulumi.com/registry/packages/command/
